name: 'Test SPN login'

on: push


jobs:
  azure_load_test:
    env:
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    
    runs-on: ubuntu-latest
    steps:

    #==================================
    # Checkout Repository
    #================================== 
    - name: Checkout GitHub Actions 
      uses: actions/checkout@v2

    #==================================
    # Setup Az Login
    #================================== 
    - name: Setup az login
      run: |
        az login --service-principal -u ${{ secrets.AZURE_AD_CLIENT_ID }} -p ${{ secrets.AZURE_AD_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_AD_TENANT_ID }}
